// Generated by gencpp from file simple_move/SimpleMoveRequest.msg
// DO NOT EDIT!


#ifndef SIMPLE_MOVE_MESSAGE_SIMPLEMOVEREQUEST_H
#define SIMPLE_MOVE_MESSAGE_SIMPLEMOVEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simple_move
{
template <class ContainerAllocator>
struct SimpleMoveRequest_
{
  typedef SimpleMoveRequest_<ContainerAllocator> Type;

  SimpleMoveRequest_()
    : distance(0.0)
    , angle(0.0)  {
    }
  SimpleMoveRequest_(const ContainerAllocator& _alloc)
    : distance(0.0)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef float _distance_type;
  _distance_type distance;

   typedef float _angle_type;
  _angle_type angle;




  typedef boost::shared_ptr< ::simple_move::SimpleMoveRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simple_move::SimpleMoveRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SimpleMoveRequest_

typedef ::simple_move::SimpleMoveRequest_<std::allocator<void> > SimpleMoveRequest;

typedef boost::shared_ptr< ::simple_move::SimpleMoveRequest > SimpleMoveRequestPtr;
typedef boost::shared_ptr< ::simple_move::SimpleMoveRequest const> SimpleMoveRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simple_move::SimpleMoveRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simple_move::SimpleMoveRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace simple_move

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::simple_move::SimpleMoveRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simple_move::SimpleMoveRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simple_move::SimpleMoveRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simple_move::SimpleMoveRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simple_move::SimpleMoveRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simple_move::SimpleMoveRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simple_move::SimpleMoveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ec24e737ddaa2f1769f4aa74f864401d";
  }

  static const char* value(const ::simple_move::SimpleMoveRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xec24e737ddaa2f17ULL;
  static const uint64_t static_value2 = 0x69f4aa74f864401dULL;
};

template<class ContainerAllocator>
struct DataType< ::simple_move::SimpleMoveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simple_move/SimpleMoveRequest";
  }

  static const char* value(const ::simple_move::SimpleMoveRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simple_move::SimpleMoveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 distance\n\
float32 angle\n\
";
  }

  static const char* value(const ::simple_move::SimpleMoveRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simple_move::SimpleMoveRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SimpleMoveRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simple_move::SimpleMoveRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simple_move::SimpleMoveRequest_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMPLE_MOVE_MESSAGE_SIMPLEMOVEREQUEST_H
